"$schema" = "schemas/schema.json"

[default]
description = "Default permissions for the speech-recognizer plugin"
permissions = [
    "allow-start-listening",
    "allow-stop-listening",
    "allow-is-available",
    "allow-request-permission",
    "allow-register-listener",
    "allow-remove-listener",
]
